version: '3.7'

services:
  postgres-container:
      image: postgres
      #container_name: db
      ports:
        - "5432:5432"
      env_file:
        - ./env/postgres.env
      networks:
        - gcsystem-net
  gcsystem-container:
    image: wisleymarques/gcsystem:latest
    ports:
      - "8000:8000"
      - "8080:8080"
    env_file:
      - ./env/system-development.env
    depends_on:
      - postgres-container
    networks:
      - gcsystem-net

networks:
  gcsystem-net:
