export const REQUEST_BASE_URL = process.env.REACT_APP_BACKEND_URL ?? 'http://localhost:8080';
//export const REQUEST_BASE_URL = 'http://192.168.15.2:8080';
export const PERMISSION_URL = 'permission'

/** EMPLOYEES REQUEST */
export const REQUEST_LOGIN_EMPLOYEES = process.env.REACT_APP_REQUEST_LOGIN_EMPLOYEES ?? ''
export const REQUEST_EMPLOYEES = process.env.REACT_APP_REQUEST_EMPLOYEES ?? '';
export const REQUEST_EMPLOYEE_SEARCH = process.env.REACT_APP_REQUEST_EMPLOYEE_SEARCH ?? '';
export const REQUEST_EMPLOYEES_TO_MODAL_ORDER_SERVICE = process.env.REACT_APP_REQUEST_EMPLOYEES_TO_MODAL_ORDER_SERVICE ?? '';

export const REQUEST_LOGIN = process.env.REACT_APP_REQUEST_LOGIN ?? '';
export const REQUEST_VALIDATE_TOKEN = process.env.REACT_APP_REQUEST_VALIDATE_TOKEN ?? '';
export const REQUEST_REQUEST_CODE = process.env.REACT_APP_REQUEST_REQUEST_CODE ?? '';
export const REQUEST_VALIDATE_CODE = process.env.REACT_APP_REQUEST_VALIDATE_CODE ?? '';
export const REQUEST_PASSWORD_CHANGE = process.env.REACT_APP_REQUEST_PASSWORD_CHANGE ?? '';

/*STATUS REQUEST */
export const REQUEST_STATUS = process.env.REACT_APP_REQUEST_STATUS ?? '';
export const REQUEST_STATUS_FROM_VIEW_CONDOMINIUM = process.env.REACT_APP_REQUEST_STATUS_FROM_VIEW_CONDOMINIUM ?? '';
export const REQUEST_STATUS_FROM_VIEW_CONTRACT = process.env.REACT_APP_REQUEST_STATUS_FROM_VIEW_CONTRACT ?? '';
export const REQUEST_STATUS_FROM_VIEW_DEBT = process.env.REACT_APP_REQUEST_STATUS_FROM_VIEW_DEBT ?? '';
export const REQUEST_STATUS_FROM_VIEW_REPAIR_REQUEST = process.env.REACT_APP_REQUEST_STATUS_FROM_VIEW_REPAIR_REQUEST ?? '';
export const REQUEST_STATUS_FROM_VIEW_ORDER_SERVICE = process.env.REACT_APP_REQUEST_STATUS_FROM_VIEW_ORDER_SERVICE ?? '';

export const REQUEST_ROLES = process.env.REACT_APP_REQUEST_ROLES ?? '';
export const REQUEST_SPECIALTIES = process.env.REACT_APP_REQUEST_SPECIALTIES ?? '';

/*lESSEES REQUEST */
export const REQUEST_LESSEES = process.env.REACT_APP_REQUEST_LESSEES ?? '';
export const REQUEST_LESSEE_SEARCH = process.env.REACT_APP_REQUEST_LESSEE_SEARCH ?? '';

/* CONDOMINIUM REQUEST */
export const REQUEST_CONDOMINIUMS = process.env.REACT_APP_REQUEST_CONDOMINIUMS ?? '';
export const REQUEST_CONDOMINIUM_SEARCH = process.env.REACT_APP_REQUEST_CONDOMINIUM_SEARCH ?? '';
export const REQUEST_CONDOMINIUM_LIST_ALL = process.env.REACT_APP_REQUEST_CONDOMINIUM_LIST_ALL ?? '';

/* CONTRACT REQUEST */
export const REQUEST_CONTRACTS = process.env.REACT_APP_REQUEST_CONTRACTS ?? '';
export const REQUEST_CONTRACT_SEARCH = process.env.REACT_APP_REQUEST_CONTRACT_SEARCH ?? '';
export const REQUEST_CONTRACTS_PRINTOUT = process.env.REACT_APP_REQUEST_CONTRACTS_PRINTOUT ?? '';

/* DEBT REQUEST */
export const REQUEST_DEBTS = process.env.REACT_APP_REQUEST_DEBTS ?? '';
export const REQUEST_DEBT_SEARCH = process.env.REACT_APP_REQUEST_DEBT_SEARCH ?? '';

/* REPAIR-REQUEST REQUEST */
export const REQUEST_REPAIR_REQUESTS = process.env.REACT_APP_REQUEST_REPAIR_REQUESTS ?? '';
export const REQUEST_REPAIR_REQUESTS_SEARCH = process.env.REACT_APP_REQUEST_REPAIR_REQUESTS_SEARCH ?? '';
export const REQUEST_REPAIR_REQUESTS_PER_STATUS_OPEN_PROGRESS_LATE = process.env.REACT_APP_REQUEST_REPAIR_REQUESTS_PER_STATUS_OPEN_PROGRESS_LATE ?? '';
export const REQUEST_REPAIR_REQUESTS_PER_ORDER_SERVICE_AND_STATUS = process.env.REACT_APP_REQUEST_REPAIR_REQUESTS_PER_ORDER_SERVICE_AND_STATUS ?? '';
export const REQUEST_REPAIR_REQUESTS_TO_MODAL_ORDER_SERVICE = process.env.REACT_APP_REQUEST_REPAIR_REQUESTS_TO_MODAL_ORDER_SERVICE ?? '';


/* TYPE-PROBLEM REQUEST */
export const REQUEST_TYPE_PROBLEM = process.env.REACT_APP_REQUEST_TYPES_PROBLEM ?? '';

/* ORDER SERVICE REQUEST */
export const REQUEST_ORDER_SERVICES = process.env.REACT_APP_REQUEST_ORDER_SERVICES ?? '';
export const REQUEST_ORDER_SERVICES_SEARCH = process.env.REACT_APP_REQUEST_ORDER_SERVICES_SEARCH ?? '';