//export const REQUEST_BASE_URL = process.env.REACT_APP_BACKEND_URL ?? 'http://localhost:8080';
export const REQUEST_BASE_URL = 'http://localhost:8080';
/** EMPLOYEES REQUEST */
export const REQUEST_LOGIN_EMPLOYEES = process.env.REACT_APP_REQUEST_LOGIN_EMPLOYEES ?? ''
export const REQUEST_EMPLOYEES = process.env.REACT_APP_REQUEST_EMPLOYEES ?? '';
export const REQUEST_EMPLOYEE_SEARCH = process.env.REACT_APP_REQUEST_EMPLOYEE_SEARCH ?? '';
export const REQUEST_LOGIN = process.env.REACT_APP_REQUEST_LOGIN ?? '';
export const REQUEST_VALIDATE_TOKEN = process.env.REACT_APP_REQUEST_VALIDATE_TOKEN ?? '';
export const REQUEST_REQUEST_CODE = process.env.REACT_APP_REQUEST_REQUEST_CODE ?? '';
export const REQUEST_VALIDATE_CODE = process.env.REACT_APP_REQUEST_VALIDATE_CODE ?? '';
export const REQUEST_PASSWORD_CHANGE = process.env.REACT_APP_REQUEST_PASSWORD_CHANGE ?? '';
export const REQUEST_STATUS = process.env.REACT_APP_REQUEST_STATUS ?? '';
export const REQUEST_ROLES = process.env.REACT_APP_REQUEST_ROLES ?? '';
export const REQUEST_SPECIALTIES = process.env.REACT_APP_REQUEST_SPECIALTIES ?? '';

/*lESSEES REQUEST */
export const REQUEST_LESSEES = process.env.REACT_APP_REQUEST_LESSEES ?? '';
export const REQUEST_LESSEE_SEARCH = process.env.REACT_APP_REQUEST_LESSEE_SEARCH ?? '';

/* CONDOMINIUM REQUEST */
export const REQUEST_CONDOMINIUMS = process.env.REACT_APP_REQUEST_CONDOMINIUMS ?? '';
export const REQUEST_CONDOMINIUM_SEARCH = process.env.REACT_APP_REQUEST_CONDOMINIUM_SEARCH ?? '';
export const REQUEST_CONDOMINIUM_LIST_ALL = process.env.REACT_APP_REQUEST_CONDOMINIUM_LIST_ALL ?? '';

/* CONTRACT REQUEST */
export const REQUEST_CONTRACTS = process.env.REACT_APP_REQUEST_CONTRACTS ?? '';
export const REQUEST_CONTRACT_SEARCH = process.env.REACT_APP_REQUEST_CONTRACT_SEARCH ?? '';
