export const LOGIN_URL = '/login/'
export const RECOVER_PASSWORD_URL = 'recoverpassword';
export const RECOVER_PASSWORD_SEND_CODE_URL = 'recoverpasswordcode';
export const RECOVER_PASSWORD_CHANGE_URL = 'changepassword';
export const EMPLOYEES_HOME_URL = "/employees";
export const LESSEES_HOME_URL = "/lessees";
export const HOME_URL = "/";
export const CONDOMINIUMS_HOME_URL = "/condominiums";
export const CONTRACTS_HOME_URL = "/contracts";
export const CONTRACTS_PRINTOUT_URL = CONTRACTS_HOME_URL + "/printout/:id";
export const DEBTS_HOME_URL = "/debts"; 
export const REPAIR_REQUESTS_HOME_URL = "/repairRequests"; 
export const ORDER_SERVICE_HOME_URL = "/orderServices"; 